[package]
name = "link-checker"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ureq = { version = "3.1.0"}
url = "2.5.0"
scraper = "0.24"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.0"
